# ===================================================================
# Identidad del microservicio
# ===================================================================
spring.application.name=usuario-servicio

# ===================================================================
# Servidor HTTP
# ===================================================================
server.port=8081

# ===================================================================
# Conexión a Base de Datos (Neon PostgreSQL en la nube)
# ===================================================================
spring.datasource.url=jdbc:postgresql://ep-bitter-sky-aqm6pnwc-pooler.c-8.us-east-1.aws.neon.tech/karubag_usuario?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_kugJ8ARMUo9s

spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# JPA / Hibernate (estrategia Code-First)
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
